/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import controller.ControllerCadFornecedor;
import controller.ControllerCadFuncionario;
import controller.ControllerCadHospede;
import controller.ControllerCadMarca;
import controller.ControllerCadModelo;
import controller.ControllerCadProduto;
import controller.ControllerCadQuarto;
import controller.ControllerCadServico;
import controller.ControllerCadVagaEstacionamento;
import controller.ControllerCadVeiculo;
import model.DAO.JPAUtil;

/**
 *
 * @author Usuario
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuItemServico = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHospede = new javax.swing.JMenuItem();
        jMenuItemQuarto = new javax.swing.JMenuItem();
        jMenuItemVeiculo1 = new javax.swing.JMenuItem();
        jMenuItemVeiculo = new javax.swing.JMenuItem();
        jMenuItemModelo = new javax.swing.JMenuItem();
        jMenuItemMarca = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        jMenu2.setText("Cadastros");

        jMenuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bomb.png"))); // NOI18N
        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(this::jMenuItemProdutoActionPerformed);
        jMenu2.add(jMenuItemProduto);

        jMenuItemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Equipment.png"))); // NOI18N
        jMenuItemServico.setText("Servico");
        jMenuItemServico.addActionListener(this::jMenuItemServicoActionPerformed);
        jMenu2.add(jMenuItemServico);

        jMenuItemFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Male.png"))); // NOI18N
        jMenuItemFuncionario.setText("Funcionário");
        jMenuItemFuncionario.addActionListener(this::jMenuItemFuncionarioActionPerformed);
        jMenu2.add(jMenuItemFuncionario);

        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Boss.png"))); // NOI18N
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuItemFornecedor.addActionListener(this::jMenuItemFornecedorActionPerformed);
        jMenu2.add(jMenuItemFornecedor);
        jMenu2.add(jSeparator1);

        jMenuItemHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/People.png"))); // NOI18N
        jMenuItemHospede.setText("Hóspede");
        jMenuItemHospede.addActionListener(this::jMenuItemHospedeActionPerformed);
        jMenu2.add(jMenuItemHospede);

        jMenuItemQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        jMenuItemQuarto.setText("Quarto");
        jMenuItemQuarto.addActionListener(this::jMenuItemQuartoActionPerformed);
        jMenu2.add(jMenuItemQuarto);

        jMenuItemVeiculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blue pin.png"))); // NOI18N
        jMenuItemVeiculo1.setText("Vaga");
        jMenuItemVeiculo1.addActionListener(this::jMenuItemVeiculo1ActionPerformed);
        jMenu2.add(jMenuItemVeiculo1);

        jMenuItemVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delivery.png"))); // NOI18N
        jMenuItemVeiculo.setText("Veiculo");
        jMenuItemVeiculo.addActionListener(this::jMenuItemVeiculoActionPerformed);
        jMenu2.add(jMenuItemVeiculo);

        jMenuItemModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/List.png"))); // NOI18N
        jMenuItemModelo.setText("Modelo");
        jMenuItemModelo.addActionListener(this::jMenuItemModeloActionPerformed);
        jMenu2.add(jMenuItemModelo);

        jMenuItemMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/How-to.png"))); // NOI18N
        jMenuItemMarca.setText("Marca");
        jMenuItemMarca.addActionListener(this::jMenuItemMarcaActionPerformed);
        jMenu2.add(jMenuItemMarca);
        jMenu2.add(jSeparator2);

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemSair.addActionListener(this::jMenuItemSairActionPerformed);
        jMenu2.add(jMenuItemSair);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Movimentos");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");

        jMenuItem2.setText("Sobre");
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unused")
    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent _evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHospedeActionPerformed
        TelaCadastroHospede telaCadastroHospede = new TelaCadastroHospede(null, true);
        ControllerCadHospede controllerCadHospede = new ControllerCadHospede(telaCadastroHospede);
        telaCadastroHospede.setVisible(true);
    }//GEN-LAST:event_jMenuItemHospedeActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        TelaCadastroFornecedor telaCadastroFornecedor = new TelaCadastroFornecedor(null, true);
        ControllerCadFornecedor controllerCadFornecedor = new ControllerCadFornecedor(telaCadastroFornecedor);
        telaCadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        TelaCadastroFuncionario telaCadastroFuncionario = new TelaCadastroFuncionario(null, true);
        ControllerCadFuncionario controllerCadFuncionario = new ControllerCadFuncionario(telaCadastroFuncionario);
        telaCadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuartoActionPerformed
        TelaCadastroQuarto telaCadastroQuarto = new TelaCadastroQuarto(null, true);
        ControllerCadQuarto controllerCadQuarto = new ControllerCadQuarto(telaCadastroQuarto);
        telaCadastroQuarto.setVisible(true);
    }//GEN-LAST:EVENT_jMenuItemQuartoActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculoActionPerformed
        TelaCadastroVeiculo telaCadastroVeiculo = new TelaCadastroVeiculo(null, true);
        ControllerCadVeiculo controllerCadVeiculo = new ControllerCadVeiculo(telaCadastroVeiculo);
        telaCadastroVeiculo.setVisible(true);
    }//GEN-LAST:event_jMenuItemVeiculoActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModeloActionPerformed
        TelaCadastroModelo telaCadastroModelo = new TelaCadastroModelo(null, true);
        ControllerCadModelo controllerCadModelo = new ControllerCadModelo(telaCadastroModelo);
        telaCadastroModelo.setVisible(true);
    }//GEN-LAST:event_jMenuItemModeloActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcaActionPerformed
        TelaCadastroMarca telaCadastroMarca = new TelaCadastroMarca(null, true);
        ControllerCadMarca controllerCadMarca = new ControllerCadMarca(telaCadastroMarca);
        telaCadastroMarca.setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcaActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicoActionPerformed
        TelaCadastroServico telaCadastroServico = new TelaCadastroServico(null, true);
        ControllerCadServico controllerCadServico = new ControllerCadServico(telaCadastroServico);
        telaCadastroServico.setVisible(true);
    }//GEN-LAST:event_jMenuItemServicoActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemVeiculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculo1ActionPerformed
        TelaCadastroVagaEstacionamento telaCadastroVagaEstacionamento = new TelaCadastroVagaEstacionamento(null, true);
        ControllerCadVagaEstacionamento controllerCadVagaEstacionamento = new ControllerCadVagaEstacionamento(telaCadastroVagaEstacionamento);
        telaCadastroVagaEstacionamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemVeiculo1ActionPerformed

    @SuppressWarnings("unused")
    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {
        TelaCadastroProduto telaCadastroProduto = new TelaCadastroProduto(null, true);
        ControllerCadProduto controllerCadProduto = new ControllerCadProduto(telaCadastroProduto);
        telaCadastroProduto.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        try {
            JPAUtil.getEntityManager().close();

            java.awt.EventQueue.invokeLater(() -> {
                new TelaMenuPrincipal().setVisible(true);
            });
        } catch (ExceptionInInitializerError | IllegalStateException t) {
            Logger.getLogger(TelaMenuPrincipal.class.getName()).log(Level.SEVERE, "Falha ao inicializar o JPA. Verifique a conexão com o banco de dados e o arquivo .env.", t);
            JOptionPane.showMessageDialog(null, "Erro Crítico: Não foi possível conectar ao Banco de Dados.\nVerifique o arquivo .env e o status do banco.", "Erro de Inicialização JPA", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemHospede;
    private javax.swing.JMenuItem jMenuItemMarca;
    private javax.swing.JMenuItem jMenuItemModelo;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemQuarto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemServico;
    private javax.swing.JMenuItem jMenuItemVeiculo;
    private javax.swing.JMenuItem jMenuItemVeiculo1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
